# -*- coding: utf-8 -*-
"""verizon-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZF_MG-tt_iR66ACTrpm7yi_fsHjhZTQ

***Authors:***


*   *Christiana Nardi*
*   *Eman Ahmed*
*   *Anne-Sophie Frederick*

**Imports and Dataframes:**
"""

#Installs
!pip install datasets
!pip install transformers datasets
!pip install transformers datasets accelerate bitsandbytes scikit-learn

#Imports
from os.path import normpath
import scipy.stats as stats
import requests
import numpy as np
import pandas as pd
import zipfile
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
import torch
from transformers import BertForSequenceClassification, BertTokenizer, GPT2Tokenizer, GPT2ForSequenceClassification, Trainer, TrainingArguments, AutoTokenizer, AutoModelForSequenceClassification
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, accuracy_score, confusion_matrix, precision_recall_curve, mean_squared_error, r2_score, log_loss, f1_score
from sklearn.preprocessing import normalize
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from datasets import Dataset
from textblob import TextBlob
from collections import Counter

kaggle_path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

print("Path to dataset files:", kaggle_path)

#Building dataframes

path = kaggle_path + "/IMDB Dataset.csv"
kaggle_df = pd.DataFrame()

#Breaking down in chunks to save RAM
chunk_size = 2500
for chunk in pd.read_csv(path, chunksize=chunk_size, nrows=10000):
    kaggle_df = pd.concat([kaggle_df, chunk], ignore_index=True)

"""**Kaggle Dataset Cleaning and Exploring:**

*Inspecting Data:*
"""

kaggle_df.shape

kaggle_df.head()

label_name = 'sentiment'
label = kaggle_df['sentiment']
features = kaggle_df.drop('sentiment', axis=1)
features

plt.figure(figsize=(8, 6))
kaggle_df['review_length'] = kaggle_df['review'].apply(len)
sns.histplot(kaggle_df['review_length'], bins=50)
plt.title('Distribution of Review Lengths')
plt.xlabel('Review Length')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(x='sentiment', y='review_length', data=kaggle_df)
plt.title('Review Length vs. Sentiment')
plt.xlabel('Sentiment')
plt.ylabel('Review Length')
plt.show()

"""*Handling Outliers:*"""

winsorized_review_length = stats.mstats.winsorize(kaggle_df['review_length'],limits=[.15,.15])
kaggle_df['winsorized_review_length'] = winsorized_review_length

kaggle_df['winsorized_review_length'] - kaggle_df['review_length']

# Box plot after Winsorization
plt.figure(figsize=(8, 6))
sns.boxplot(x='sentiment', y='winsorized_review_length', data=kaggle_df)
plt.title('Winsorized Review Length vs. Sentiment')
plt.xlabel('Sentiment')
plt.ylabel('Winsorized Review Length')
plt.show()

"""*Checking for Missing Data:*"""

nan_count = kaggle_df.isnull().sum()
nan_count

"""**Feature Engineering:**"""

reviews=kaggle_df['review'].tolist()
tokens=[review.split() for review in reviews]
# Print tokenized reviews (First 5 for readability)
print("Tokenized Reviews (first 5):")
for i, review_tokens in enumerate(tokens[:5]):
    print(f"Review {i+1}: {review_tokens}")

# Calculate sentiment scores for each tokenized review
sentiment_scores = [TextBlob(' '.join(review)).sentiment.polarity for review in tokens]
print(sentiment_scores)  # List of sentiment scores for each review
# Print sentiment scores (First 5 for readability)
print("\nSentiment Scores (first 5):")


for i, score in enumerate(sentiment_scores[:5]):
    print(f"Review {i+1}: Sentiment Score = {score}")
#positive sentiment score means positive
#negative sentiment score means negative
#0 sentiment score means 0

#Calculate the length of each review (number of words in each review)
review_lengths = [len(review) for review in tokens]

# Calculate word frequencies (word count for each review)
word_frequencies = []
for review in tokens:
    word_freq = Counter(review)  # Count frequency of each word in the review
    word_frequencies.append(word_freq)

"""**Model Testing & Selection:**"""

#Sample data to save RAM
df_sample = kaggle_df.sample(frac=.1, random_state=1234)

#Creating labeled examples
y=kaggle_df[label_name]
X=kaggle_df[['review']]

#Creating testing and training sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=1234)

#Getting examples
sample_fraction = 0.1
X_sample = X.sample(frac=sample_fraction, random_state=1234)
y_sample = y.sample(frac=sample_fraction, random_state=1234)

#Creating testing and training sets
X_train, X_test, y_train, y_test = train_test_split(
    X_sample, y_sample, test_size=0.5, random_state=1234
)

#Using raw text
X_train_llm = X_train['review']
X_test_llm = X_test['review']

#Training with BERT

#Converting labels to numerical values
kaggle_df['label'] = kaggle_df['sentiment'].map({'positive': 1, 'negative': 0})

#Training the model
dataset = Dataset.from_pandas(kaggle_df[['review', 'label']])

train_dataset, val_dataset = dataset.train_test_split(test_size=0.2).values()

model_name = 'prajjwal1/bert-tiny'
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForSequenceClassification.from_pretrained(model_name, num_labels=2)

#Preprocessing the data
def preprocess_function(examples):
    return tokenizer(examples['review'], padding="max_length", truncation=True, max_length=201)

train_dataset = train_dataset.map(preprocess_function, batched=True)
val_dataset = val_dataset.map(preprocess_function, batched=True)

#Defining the training arguments
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=2,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=10,
    gradient_accumulation_steps=2,
)

#Creating a trainer object
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

#Training the model
trainer.train()


eval_results = trainer.evaluate()
print(eval_results)

#Saving the model
trainer.save_model('./trained_bert_model')

#Making predictions with BERT
predictions = trainer.predict(val_dataset)
predicted_labels = predictions.predictions.argmax(-1)
true_labels = predictions.label_ids
predicted_probs = predictions.predictions

#Evaluating accuracy score, log loss, and confusion matrix
acc_bert = accuracy_score(true_labels, predicted_labels)
ll_bert = log_loss(true_labels, predicted_probs)
cm_bert = confusion_matrix(true_labels, predicted_labels)

print('BERT Model: \naccuracy score: ' + str(acc_bert))
print(f"Log Loss: {ll_bert}")
print("Confusion Matrix:")
print(cm_bert)

#Training with LaMa

#Converting labels to numerical values
kaggle_df['label'] = kaggle_df['sentiment'].map({'positive': 1, 'negative': 0})

#Training the model
model_name = "google/flan-t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

#Preprocessing the data
def preprocess_function(examples):
    return tokenizer(examples['review'], padding="max_length", truncation=True, max_length=201)

train_dataset = train_dataset.map(preprocess_function, batched=True)
val_dataset = val_dataset.map(preprocess_function, batched=True)

#Defining the training arguments
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=2,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=10,
    gradient_accumulation_steps=2,
)

#Creating a trainer object
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

#Training the model
trainer.train()


eval_results = trainer.evaluate()
print(eval_results)

#Saving the model
trainer.save_model('./trained_lama_model')

#Making predictions with LaMa
predictions = trainer.predict(val_dataset)
predicted_probs = predictions.predictions[0]
predicted_labels = predicted_probs.argmax(-1)

true_labels = predictions.label_ids

#Evaluating accuracy score, log loss, and confusion matrix
acc_lama = accuracy_score(true_labels, predicted_labels)
ll_lama = log_loss(true_labels, predicted_probs)
cm_lama = confusion_matrix(true_labels, predicted_labels)

print('LaMa Model: \naccuracy score: ' + str(acc_lama))
print(f"Log Loss: {ll_lama}")
print("Confusion Matrix:")
print(cm_lama)

#Training with GPT

#Training the model
model_name = "gpt2"
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = GPT2ForSequenceClassification.from_pretrained(model_name, num_labels=2)

tokenizer.pad_token = tokenizer.eos_token
model.config.pad_token_id = tokenizer.eos_token_id

#Preprocessing the data
def preprocess_function(examples):
    return tokenizer(examples['review'], padding="max_length", truncation=True, max_length=201)


train_dataset = train_dataset.map(preprocess_function, batched=True)
val_dataset = val_dataset.map(preprocess_function, batched=True)

#Defining the training arguments
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=2,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=10,
    gradient_accumulation_steps=2,
)

#Creating a trainer object
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

#Training the model
trainer.train()


eval_results = trainer.evaluate()
print(eval_results)

#Saving the model
trainer.save_model('./trained_gpt_model')

#Making predictions with GPT
predictions = trainer.predict(val_dataset)
predicted_probs = predictions.predictions
predicted_labels = predicted_probs.argmax(-1)

true_labels = predictions.label_ids

#Evaluating accuracy score, log loss, and confusion matrix
acc_gpt = accuracy_score(true_labels, predicted_labels)
ll_gpt = log_loss(true_labels, predicted_probs)
cm_gpt = confusion_matrix(true_labels, predicted_labels)

print('GPT Model: \naccuracy score: ' + str(acc_gpt))
print(f"Log Loss: {ll_gpt}")
print("Confusion Matrix:")
print(cm_gpt)

"""**Comparing Model Performances:**"""

def plot_confusion_matrix(cm, model_name):
  """Plots the confusion matrix for a given model."""
  plt.figure(figsize=(6, 4))
  sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
              xticklabels=['Negative', 'Positive'],
              yticklabels=['Negative', 'Positive'])
  plt.title(f"Confusion Matrix for {model_name}")
  plt.xlabel("Predicted Label")
  plt.ylabel("True Label")
  plt.show()

plot_confusion_matrix(cm_bert, "BERT")
plot_confusion_matrix(cm_lama, "LaMa")
plot_confusion_matrix(cm_gpt, "GPT")

